# Generated by Django 4.2.30 on 2026-04-16 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadLetterQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("failure_reason", models.TextField()),
                (
                    "error_trace",
                    models.JSONField(
                        default=dict,
                        help_text="JSONB: full exception info {type, message, traceback, context}",
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("last_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_retry", "Pending Retry"),
                            ("exhausted", "Exhausted"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending_retry",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dead Letter Queue Entry",
                "verbose_name_plural": "Dead Letter Queue",
            },
        ),
        migrations.CreateModel(
            name="RawWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        help_text="Provider.resource.action e.g. jira.issue.created",
                        max_length=100,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="JSONB: raw webhook body — immutable after creation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="SHA-256(integration_id + event_type + payload_hash)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_events",
                        to="integrations.integration",
                    ),
                ),
                (
                    "integration_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_events",
                        to="integrations.integrationaccount",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_events",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Webhook Event",
                "verbose_name_plural": "Raw Webhook Events",
            },
        ),
    ]
