[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/lib/docker/containers/*/*.log
    Parser       docker
    Tag          tetragon
    Path_Key     filename

[FILTER]
    Name         grep
    Match        tetragon
    Regex        log "matchActions"

[OUTPUT]
    Name         http
    Match        tetragon
    Host         parseable
    Port         8000
    URI          /api/v1/logstream/tetragon
    Format       json
    Header       Authorization Basic ${PARSEABLE_BASIC_AUTH}
    Header       X-P-Stream tetragon
