"""
zip_builder.py
Builds an in-memory ZIP for a Problem and returns the raw bytes.
"""

import zipfile
from io import BytesIO

from .models import Problem


_FRONTEND_PKG_JSON = """\
{
  "name": "startup-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.2.1",
    "vite": "^5.1.4"
  }
}
"""

_VITE_CONFIG = """\
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 5174,
    proxy: {
      '/api': 'http://localhost:8000',
    },
  },
})
"""

_INDEX_HTML = """\
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Startup Project</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""

_MAIN_JSX = """\
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
"""


def build_zip(problem: Problem) -> bytes:
    """Return ZIP bytes for the given Problem."""
    buf = BytesIO()
    slug = problem.slug

    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:

        def add(path: str, content: str):
            if content:
                zf.writestr(f"{slug}/{path}", content.encode("utf-8", errors="replace"))

        # ── Root README ────────────────────────────────────────────────────
        root_readme = f"""\
# {problem.title}

**Category:** {problem.category}  
**Source:** {problem.source_name}  
**Downloaded from:** Startup Problem Marketplace  

---

## Package Contents

| File | Description |
|------|-------------|
| `article.md` | Original news article that inspired this package |
| `problem.txt` | Deep root-cause business problem analysis |
| `solution.txt` | Proposed startup solution concept |
| `architecture.txt` | Complete open-source tech stack & system design |
| `implementation_plan.txt` | Step-by-step developer build plan |
| `monetization.txt` | Revenue model, pricing tiers & GTM strategy |
| `sample_code/` | Runnable starter codebase to build from |

---

## Quick Start

```bash
cd sample_code
# See sample_code/README.md for setup instructions
```

---

*Generated by Startup Problem Marketplace — all solutions use 100% free/open-source tech.*
"""
        add("README.md", root_readme)

        # ── Documents ──────────────────────────────────────────────────────
        add("article.md", problem.article_md or "")
        add("problem.txt", problem.problem_txt or "")
        add("solution.txt", problem.solution_txt or "")
        add("architecture.txt", problem.architecture_txt or "")
        add("implementation_plan.txt", problem.implementation_plan_txt or "")
        add("monetization.txt", problem.monetization_txt or "")

        # ── Sample code — backend ──────────────────────────────────────────
        add("sample_code/README.md", problem.sample_readme or "")
        add("sample_code/backend/main.py", problem.sample_backend_main or "")
        add("sample_code/backend/models.py", problem.sample_backend_models or "")
        add("sample_code/backend/services.py", problem.sample_backend_services or "")
        add("sample_code/backend/requirements.txt", problem.sample_backend_requirements or "")

        # backend .env example
        add(
            "sample_code/backend/.env.example",
            "DATABASE_URL=sqlite:///./app.db\n"
            "OLLAMA_HOST=http://localhost:11434\n"
            "OLLAMA_MODEL=llama3:8b\n",
        )

        # ── Sample code — frontend ─────────────────────────────────────────
        add("sample_code/frontend/package.json", _FRONTEND_PKG_JSON)
        add("sample_code/frontend/vite.config.js", _VITE_CONFIG)
        add("sample_code/frontend/index.html", _INDEX_HTML)
        add("sample_code/frontend/src/main.jsx", _MAIN_JSX)
        add("sample_code/frontend/src/App.jsx", problem.sample_frontend_app or "")

        # ── Docker Compose ─────────────────────────────────────────────────
        docker_compose = f"""\
version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/app
      - OLLAMA_HOST=http://host.docker.internal:11434
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"

volumes:
  pgdata:
"""
        add("sample_code/docker-compose.yml", docker_compose)

    return buf.getvalue()
