# Generated by Django 4.2.30 on 2026-04-16 00:09

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('processing', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_user_id', models.CharField(help_text="User's ID in the source provider system", max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar_url', models.URLField(blank=True)),
                ('provider_metadata', models.JSONField(default=dict)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='integrations.integration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, help_text='Linked internal Django user (if resolved)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Identity',
                'verbose_name_plural': 'External Identities',
            },
        ),
        migrations.CreateModel(
            name='UnifiedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_ticket_id', models.CharField(help_text='Ticket ID in the source provider (e.g. PROJ-123)', max_length=255)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('normalized_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('resolved', 'Resolved')], max_length=20)),
                ('normalized_type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('task', 'Task'), ('epic', 'Epic'), ('story', 'Story'), ('subtask', 'Subtask'), ('other', 'Other')], default='task', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='ISO-8601 date', null=True)),
                ('provider_metadata', models.JSONField(default=dict, help_text='JSONB: provider-specific raw fields (sprint, story points, etc.)')),
                ('labels', models.JSONField(default=list, help_text='JSONB list of label strings')),
                ('source_created_at', models.DateTimeField(blank=True, help_text='When created in source system', null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, help_text='When last updated in source system', null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='tickets.externalidentity')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='integrations.integration')),
                ('integration_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='integrations.integrationaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.organization')),
                ('processing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='processing.processingrun')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to='tickets.externalidentity')),
            ],
            options={
                'verbose_name': 'Unified Ticket',
                'verbose_name_plural': 'Unified Tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('blocks', 'Blocks'), ('is_blocked_by', 'Is Blocked By'), ('duplicates', 'Duplicates'), ('is_duplicate_of', 'Is Duplicate Of'), ('relates_to', 'Relates To'), ('clones', 'Clones')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_links', to='accounts.organization')),
                ('source_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='tickets.unifiedticket')),
                ('target_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='tickets.unifiedticket')),
            ],
            options={
                'verbose_name': 'Ticket Link',
                'verbose_name_plural': 'Ticket Links',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_comment_id', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True, help_text='Rendered HTML if available')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note vs. public comment')),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='tickets.externalidentity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to='accounts.organization')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.unifiedticket')),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('status_change', 'Status Change'), ('assignment', 'Assignment'), ('comment', 'Comment'), ('label', 'Label'), ('priority', 'Priority'), ('custom', 'Custom')], max_length=30)),
                ('changes', models.JSONField(default=dict, help_text="JSONB: {field_name: {from: '...', to: '...'}}")),
                ('occurred_at', models.DateTimeField(help_text='When this activity happened in the source system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to='tickets.externalidentity')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tickets.unifiedticket')),
            ],
            options={
                'verbose_name': 'Ticket Activity',
                'verbose_name_plural': 'Ticket Activities',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=django.contrib.postgres.indexes.GinIndex(fields=['provider_metadata'], name='ticket_prov_meta_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(condition=models.Q(('normalized_status__in', ['open', 'in_progress', 'blocked'])), fields=['normalized_status'], name='ticket_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(fields=['integration', 'external_ticket_id'], name='ticket_int_ext_id_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(fields=['assignee', 'normalized_status'], name='ticket_assignee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(fields=['normalized_status', 'normalized_type'], name='ticket_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(fields=['normalized_status'], include=('id', 'title'), name='ticket_status_covering_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(fields=['-updated_at'], name='ticket_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedticket',
            index=models.Index(fields=['organization', 'normalized_status'], name='ticket_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedticket',
            constraint=models.UniqueConstraint(fields=('integration', 'external_ticket_id'), name='unique_ticket_per_integration'),
        ),
        migrations.AddConstraint(
            model_name='ticketlink',
            constraint=models.UniqueConstraint(fields=('source_ticket', 'target_ticket', 'link_type'), name='unique_ticket_link'),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', '-source_created_at'], name='comment_ticket_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticketcomment',
            constraint=models.UniqueConstraint(condition=models.Q(('external_comment_id', ''), _negated=True), fields=('ticket', 'external_comment_id'), name='unique_external_comment'),
        ),
        migrations.AddIndex(
            model_name='ticketactivity',
            index=models.Index(fields=['ticket', '-occurred_at'], name='activity_ticket_time_idx'),
        ),
        migrations.AddIndex(
            model_name='externalidentity',
            index=models.Index(fields=['organization', 'integration'], name='extidentity_org_int_idx'),
        ),
        migrations.AddIndex(
            model_name='externalidentity',
            index=models.Index(fields=['email'], name='extidentity_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.UniqueConstraint(fields=('integration', 'external_user_id'), name='unique_external_identity'),
        ),
    ]
