# Generated by Django 4.2.30 on 2026-04-16 00:09

import uuid

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappedPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mapped_data",
                    models.JSONField(
                        help_text="JSONB: normalized ticket fields from LLM mapper"
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(
                        default="v1",
                        help_text="Version of the UnifiedTicket mapping schema",
                        max_length=20,
                    ),
                ),
                ("mapped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapped_payloads",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapped Payload",
                "verbose_name_plural": "Mapped Payloads",
            },
        ),
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("mapping", "Mapping"),
                            ("validating", "Validating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "attempt_count",
                    models.IntegerField(
                        default=1,
                        help_text="Which LangGraph mapper retry attempt (1–3)",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        help_text="LLM model used, e.g. gpt-4o",
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Provider name from TicketState.source", max_length=50
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_runs",
                        to="accounts.organization",
                    ),
                ),
                (
                    "raw_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_runs",
                        to="events.rawwebhookevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Run",
                "verbose_name_plural": "Processing Runs",
            },
        ),
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_valid", models.BooleanField()),
                (
                    "validation_errors",
                    models.JSONField(
                        default=list,
                        help_text="JSONB list of error strings from validator node",
                    ),
                ),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mapped_payload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_result",
                        to="processing.mappedpayload",
                    ),
                ),
                (
                    "processing_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_result",
                        to="processing.processingrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Result",
                "verbose_name_plural": "Validation Results",
            },
        ),
        migrations.AddField(
            model_name="mappedpayload",
            name="processing_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapped_payload",
                to="processing.processingrun",
            ),
        ),
        migrations.CreateModel(
            name="ProcessingStepLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_name",
                    models.CharField(
                        choices=[
                            ("fetcher", "Fetcher"),
                            ("mapper", "Mapper"),
                            ("validator", "Validator"),
                            ("persist", "Persist"),
                            ("dlq", "DLQ"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        help_text="Step order within the run (1, 2, 3…)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True, help_text="JSONB: node input state", null=True
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, help_text="JSONB: node output state", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_logs",
                        to="processing.processingrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Step Log",
                "verbose_name_plural": "Processing Step Logs",
                "ordering": ["processing_run", "sequence"],
                "indexes": [
                    models.Index(
                        fields=["processing_run", "sequence"],
                        name="steplog_run_sequence_idx",
                    ),
                    models.Index(fields=["-logged_at"], name="steplog_logged_at_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="processingrun",
            index=models.Index(
                fields=["organization", "status"], name="procrun_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingrun",
            index=models.Index(fields=["-started_at"], name="procrun_started_at_idx"),
        ),
        migrations.AddIndex(
            model_name="mappedpayload",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["mapped_data"], name="mapped_payload_gin_idx"
            ),
        ),
    ]
