apiVersion: v1
kind: Service
metadata:
  name: agent-service
spec:
  type: NodePort
  selector:
    app: agent-service
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30014
      protocol: TCP
