apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lerna-platform
  namespace: lerna
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  rules:
    - host: lerna.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lerna-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lerna-dashboard
                port:
                  number: 3000
