apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-service
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      containers:
        - name: messaging-service
          image: nova-chat-messaging-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: MONGO_URI
              value: mongodb://mongo:27017/nova-chat
            - name: MAX_CONNECTIONS
              value: "2"
            - name: SECURITY_SERVICE_URL
              value: http://security-service:3005
