apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  type: NodePort
  selector:
    app: security-service
  ports:
    - port: 3005
      targetPort: 3005
      nodePort: 30015
      protocol: TCP
