# Generated by Django 4.2.30 on 2026-04-16 00:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label for this key", max_length=255
                    ),
                ),
                ("hashed_key", models.CharField(max_length=255, unique=True)),
                (
                    "prefix",
                    models.CharField(
                        help_text="First 8 chars of raw key for display", max_length=10
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="JSONB list of allowed scopes, e.g. ['events.ingest', 'tickets.upsert']",
                    ),
                ),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Dot-notation action, e.g. 'ticket.upsert', 'integration.create'",
                        max_length=100,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.CharField(blank=True, max_length=255)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="JSONB: {before: {...}, after: {...}}",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="security.apikey",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="auditlog_org_created_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="auditlog_resource_idx",
                    ),
                    models.Index(fields=["actor"], name="auditlog_actor_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["organization", "is_active"], name="apikey_org_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["hashed_key"], name="apikey_hash_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["expires_at"], name="apikey_expiry_idx"),
        ),
    ]
