# Generated by Django 4.2.30 on 2026-04-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="permissions",
            field=models.JSONField(
                default=list,
                help_text="JSONB list of allowed scopes, e.g. ['events.ingest']",
            ),
        ),
    ]
