# Generated by Django 4.2.30 on 2026-04-16 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text="JSONB: cached HTTP response body",
                        null=True,
                    ),
                ),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Records auto-cleaned after this timestamp"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_keys",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Idempotency Key",
                "verbose_name_plural": "Idempotency Keys",
            },
        ),
        migrations.CreateModel(
            name="SyncCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checkpoint_key",
                    models.CharField(
                        help_text="Identifies what is being synced, e.g. 'jira_issues_cursor'",
                        max_length=255,
                    ),
                ),
                (
                    "checkpoint_value",
                    models.JSONField(
                        default=dict,
                        help_text="JSONB: {cursor, page_token, since_date, page_number, etc.}",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "records_synced",
                    models.IntegerField(
                        default=0, help_text="Record count from last sync run"
                    ),
                ),
                (
                    "integration_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_checkpoints",
                        to="integrations.integrationaccount",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_checkpoints",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Checkpoint",
                "verbose_name_plural": "Sync Checkpoints",
                "indexes": [
                    models.Index(
                        fields=["organization", "integration_account"],
                        name="checkpoint_org_account_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="synccheckpoint",
            constraint=models.UniqueConstraint(
                fields=("integration_account", "checkpoint_key"),
                name="unique_sync_checkpoint",
            ),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["expires_at"], name="idempkey_expires_idx"),
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(
                fields=["organization", "key"], name="idempkey_org_key_idx"
            ),
        ),
    ]
