apiVersion: v1
kind: Service
metadata:
  name: autonomous-recovery-service
spec:
  selector:
    app: autonomous-recovery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort