# Generated by Django 4.2.30 on 2026-04-16 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                (
                    "layout",
                    models.JSONField(
                        default=dict,
                        help_text="JSONB: grid layout config for the frontend renderer",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_shared", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("trend", "Trend"),
                            ("anomaly", "Anomaly"),
                            ("summary", "Summary"),
                            ("prediction", "Prediction"),
                            ("recommendation", "Recommendation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "content",
                    models.JSONField(
                        help_text="JSONB: structured insight content (varies by type)"
                    ),
                ),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "generated_by",
                    models.CharField(
                        help_text="Agent or model that produced this insight",
                        max_length=100,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True, help_text="0.0–1.0 confidence", null=True
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight",
                "verbose_name_plural": "Insights",
            },
        ),
        migrations.CreateModel(
            name="SavedQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "natural_language_query",
                    models.TextField(help_text="The user's question in plain English"),
                ),
                (
                    "resolved_filters",
                    models.JSONField(
                        default=dict, help_text="JSONB: compiled DRF filter parameters"
                    ),
                ),
                (
                    "result_cache",
                    models.JSONField(
                        blank=True, help_text="JSONB: last query result set", null=True
                    ),
                ),
                ("cache_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_queries",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Query",
                "verbose_name_plural": "Saved Queries",
            },
        ),
        migrations.CreateModel(
            name="InsightSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="insights.insight",
                    ),
                ),
                (
                    "raw_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_sources",
                        to="events.rawwebhookevent",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_sources",
                        to="tickets.unifiedticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight Source",
                "verbose_name_plural": "Insight Sources",
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("ticket_count", "Ticket Count"),
                            ("trend_chart", "Trend Chart"),
                            ("assignee_breakdown", "Assignee Breakdown"),
                            ("status_pie", "Status Pie"),
                            ("saved_query_table", "Saved Query Table"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="JSONB: widget-specific config (filters, date range, chart type)",
                    ),
                ),
                (
                    "position",
                    models.JSONField(
                        default=dict, help_text="JSONB: grid position {x, y, w, h}"
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="insights.dashboard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
            },
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["organization", "insight_type"], name="insight_org_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["organization", "-period_start"], name="insight_org_period_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                fields=("organization", "slug"), name="unique_dashboard_slug_per_org"
            ),
        ),
    ]
